import React from "react"
import { Grid, IconButton, MenuItem, Select } from "@mui/material"
import CalendarIcon from "@mui/icons-material/CalendarTodayOutlined"
import { rem } from "polished"

import {
  StyledReferralTab as StyledLocationsTab,
  StyledReferralTabForm as StyledLocationsTabForm,
  StyledReferralTabFormActions as StyledLocationsTabFormActions,
  StyledReferralTabFormField as StyledLocationsTabFormField,
  StyledReferralTabFormItem as StyledLocationsTabFormItem,
  StyledReferralTabFormLabel as StyledLocationsTabFormLabel,
} from "./AddCustomerPage.styled"
import { ContainedButton, OutlinedButton } from "@/components/commons/Button"

const LocationsTab = () => {
  return (
    <StyledLocationsTab>
      <StyledLocationsTabForm>
        <Grid container spacing={2}>
          <Grid item xs={12} lg={4}>
            <StyledLocationsTabFormItem>
              <StyledLocationsTabFormLabel>
                Date generated
              </StyledLocationsTabFormLabel>
              <StyledLocationsTabFormField
                value={new Date().toLocaleDateString()}
                endAdornment={
                  <IconButton size="small" sx={{ mr: rem("8px") }}>
                    <CalendarIcon />
                  </IconButton>
                }
              />
            </StyledLocationsTabFormItem>
            <StyledLocationsTabFormItem>
              <StyledLocationsTabFormLabel>
                Date activated
              </StyledLocationsTabFormLabel>
              <StyledLocationsTabFormField
                placeholder={new Date().toLocaleDateString()}
                endAdornment={
                  <IconButton size="small" sx={{ mr: rem("8px") }}>
                    <CalendarIcon />
                  </IconButton>
                }
              />
            </StyledLocationsTabFormItem>
          </Grid>
          <Grid item xs={12} lg={4}>
            <StyledLocationsTabFormItem>
              <StyledLocationsTabFormLabel>
                Generated by
              </StyledLocationsTabFormLabel>
              <Select
                defaultValue="none"
                input={<StyledLocationsTabFormField />}
              >
                <MenuItem disabled value="none">
                  Choose from list
                </MenuItem>
              </Select>
            </StyledLocationsTabFormItem>
            <StyledLocationsTabFormItem>
              <StyledLocationsTabFormLabel>
                Generated for
              </StyledLocationsTabFormLabel>
              <Select
                defaultValue="none"
                input={<StyledLocationsTabFormField />}
              >
                <MenuItem disabled value="none">
                  Choose from list
                </MenuItem>
              </Select>
            </StyledLocationsTabFormItem>
          </Grid>
          <Grid item xs={12} lg={4}></Grid>
        </Grid>
        <StyledLocationsTabFormActions>
          <OutlinedButton grey sx={{ mr: rem("12px") }}>
            Cancel
          </OutlinedButton>
          <ContainedButton>Save</ContainedButton>
        </StyledLocationsTabFormActions>
      </StyledLocationsTabForm>
    </StyledLocationsTab>
  )
}

export default LocationsTab
