import React from "react"
import { Grid, IconButton, MenuItem, Select } from "@mui/material"
import {
  StyledReferralTab,
  StyledReferralTabForm,
  StyledReferralTabFormActions,
  StyledReferralTabFormField,
  StyledReferralTabFormItem,
  StyledReferralTabFormLabel,
} from "./AddCustomerPage.styled"
import CalendarIcon from "@mui/icons-material/CalendarTodayOutlined"
import { rem } from "polished"
import { ContainedButton, OutlinedButton } from "../commons/Button"

const ReferralTab = () => {
  return (
    <StyledReferralTab>
      <StyledReferralTabForm>
        <Grid container spacing={2}>
          <Grid item xs={12} lg={4}>
            <StyledReferralTabFormItem>
              <StyledReferralTabFormLabel>
                Date generated
              </StyledReferralTabFormLabel>
              <StyledReferralTabFormField
                value={new Date().toLocaleDateString()}
                endAdornment={
                  <IconButton size="small" sx={{ mr: rem("8px") }}>
                    <CalendarIcon />
                  </IconButton>
                }
              />
            </StyledReferralTabFormItem>
            <StyledReferralTabFormItem>
              <StyledReferralTabFormLabel>
                Date activated
              </StyledReferralTabFormLabel>
              <StyledReferralTabFormField
                placeholder={new Date().toLocaleDateString()}
                endAdornment={
                  <IconButton size="small" sx={{ mr: rem("8px") }}>
                    <CalendarIcon />
                  </IconButton>
                }
              />
            </StyledReferralTabFormItem>
          </Grid>
          <Grid item xs={12} lg={4}>
            <StyledReferralTabFormItem>
              <StyledReferralTabFormLabel>
                Generated by
              </StyledReferralTabFormLabel>
              <Select
                defaultValue="none"
                input={<StyledReferralTabFormField />}
              >
                <MenuItem disabled value="none">
                  Choose from list
                </MenuItem>
              </Select>
            </StyledReferralTabFormItem>
            <StyledReferralTabFormItem>
              <StyledReferralTabFormLabel>
                Generated for
              </StyledReferralTabFormLabel>
              <Select
                defaultValue="none"
                input={<StyledReferralTabFormField />}
              >
                <MenuItem disabled value="none">
                  Choose from list
                </MenuItem>
              </Select>
            </StyledReferralTabFormItem>
          </Grid>
          <Grid item xs={12} lg={4}></Grid>
        </Grid>
        <StyledReferralTabFormActions>
          <OutlinedButton grey sx={{ mr: rem("12px") }}>
            Cancel
          </OutlinedButton>
          <ContainedButton>Save</ContainedButton>
        </StyledReferralTabFormActions>
      </StyledReferralTabForm>
    </StyledReferralTab>
  )
}

export default ReferralTab
