export const GATSBY_TIMEZONE_API_KEY = "GATSBY_TIMEZONE_API_KEY"
export const GATSBY_ARRIUM_PROD_URL = "GATSBY_ARRIUM_PROD_URL"
export const GATSBY_GEOLOCATION_API_KEY = "GATSBY_GEOLOCATION_API_KEY"
export const GATSBY_AMAZON_CLIENT_ID = "GATSBY_AMAZON_CLIENT_ID"

const ENV_VARS = {
  GATSBY_TIMEZONE_API_KEY,
  GATSBY_ARRIUM_PROD_URL,
  GATSBY_GEOLOCATION_API_KEY,
  GATSBY_AMAZON_CLIENT_ID,
} as const

export default ENV_VARS
